### PR TITLE
Add issues tag, Fix typo in the lang file, copy readme.

### PR DESCRIPTION
**Pull request by K0-RR**
- README - You might want to change it as IDK if all the features are the same. Mention about the copper and amethyst tools should be added.
Also maybe move the CF link to the "About" section (this can't be done in a pr AFAIK).

### CODE REVIEW

**Review by skylorbeck — COMMENTED** [review]
I skipped the readme in favor of the infographic. Originally I was using the readme to make the curseforge page easier to update but WYSIWYG is so terrible on CF that I just abandoned that.

**Review by skylorbeck — APPROVED** [review]
Thank you!

**Comment by K0-RR** [comment]
Currently, I'm in the middle of translating 10 mods at once and... it's too much, I will finish this translation for sure but I need a few days as I'm going away from home.

https://github.com/Skylortrexler/Sentimentality3/blob/98dd7dfdf27a748545357f89af9a7aa37d3d04f2/src/main/resources/assets/sentimentality3/lang/en_us.json#L94 Duplicating this so many times is kinda, uh, can't it be done in any other way?

>I skipped the readme in favor of the infographic

Ok, so you want me to remove the readme text and add the infographics in its place?

**Comment by skylorbeck** [comment]
> Ok, so you want me to remove the readme text and add the infographics in its place?

Firstly, I want you to know that you don't have to do anything if you don't want to and I'm not comfortable telling you to do work for me. But I would like the readme removed before I merge this pull.

> Currently, I'm in the middle of translating 10 mods at once and... it's too much, I will finish this translation for sure but I need a few days as I'm going away from home.

Absolutely no problem.
 
> Duplicating this so many times is kinda, uh, can't it be done in any other way?

If I can find a way, I will but currently that is because of autoconfig. Using ` @ConfigEntry.Gui.Tooltip` causes a new translatable text to be created with the identifier being that of the variable. I have no idea how to change that behavior.

**Comment by skylorbeck** [comment]
Just pushed a change to the tooltip behavior, should make it more... palatable.

**Comment by K0-RR** [comment]
Sooooo Github broke my repo? I clicked on `fetch upstream` and got `500 error`. After this, I can't access the patch-1 branch... https://github.com/RDKRACZ/Sentimentality3/tree/patch-1

Btw for some reason, this one didn't vanish when You improved the tooltip behavior https://github.com/RDKRACZ/Sentimentality3/blob/master/src/main/resources/assets/sentimentality3/lang/en_us.json#L10 but all the ones after this https://github.com/Skylortrexler/Sentimentality3/blob/master/src/main/resources/assets/sentimentality3/lang/en_us.json#L70 disappeared. No issue with this at all, just wondering why.

**Comment by skylorbeck** [comment]
Oh I forgot to delete that first one. And the second one is the replacement for the giant cluster.

Weird about the repo. I have no idea what's up with that.

**Comment by skylorbeck** [comment]
Looks like your repo is back

**Comment by K0-RR** [comment]
Yeah, this was so weird, I was in the middle of writing to the support. The Desktop client was even weirder telling my this

Screenshot from 2021-08-05 00-24-45

when trying to fetch origin or even better, this 

Screenshot from 2021-08-05 00-25-52

when trying to switch to upstream branch...

This was displayed when trying to clone

Screenshot from 2021-08-05 00-26-33

**Comment by skylorbeck** [comment]
I just had an issue trying to push as well. Took around a minute to push the lang file.

**Review by skylorbeck — APPROVED** [review]

**Pull request merged**
